/*
 * generated by Xtext
 */
package org.xtext.example.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CupidoGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class CupidoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cupido");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cSchemataParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cCommitmentsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCommitmentsCommitmentParserRuleCall_1_0 = (RuleCall)cCommitmentsAssignment_1.eContents().get(0);
		
		//Cupido:
		//	Schemata commitments+=Commitment*;
		@Override public ParserRule getRule() { return rule; }

		//Schemata commitments+=Commitment*
		public Group getGroup() { return cGroup; }

		//Schemata
		public RuleCall getSchemataParserRuleCall_0() { return cSchemataParserRuleCall_0; }

		//commitments+=Commitment*
		public Assignment getCommitmentsAssignment_1() { return cCommitmentsAssignment_1; }

		//Commitment
		public RuleCall getCommitmentsCommitmentParserRuleCall_1_0() { return cCommitmentsCommitmentParserRuleCall_1_0; }
	}

	public class SchemataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Schemata");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cSCHEMATerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cSchemataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSchemataEventRelationParserRuleCall_1_0 = (RuleCall)cSchemataAssignment_1.eContents().get(0);
		
		//Schemata:
		//	SCHEMA schemata+=EventRelation+;
		@Override public ParserRule getRule() { return rule; }

		//SCHEMA schemata+=EventRelation+
		public Group getGroup() { return cGroup; }

		//SCHEMA
		public RuleCall getSCHEMATerminalRuleCall_0() { return cSCHEMATerminalRuleCall_0; }

		//schemata+=EventRelation+
		public Assignment getSchemataAssignment_1() { return cSchemataAssignment_1; }

		//EventRelation
		public RuleCall getSchemataEventRelationParserRuleCall_1_0() { return cSchemataEventRelationParserRuleCall_1_0; }
	}

	public class EventRelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventRelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_0_0 = (RuleCall)cEventAssignment_0.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cParamsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParamsParamParserRuleCall_2_0 = (RuleCall)cParamsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cCOMMATerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Assignment cParamsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cParamsParamParserRuleCall_3_1_0 = (RuleCall)cParamsAssignment_3_1.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cKEYTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cKeyParamsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cKeyParamsParamParserRuleCall_6_0 = (RuleCall)cKeyParamsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final RuleCall cCOMMATerminalRuleCall_7_0 = (RuleCall)cGroup_7.eContents().get(0);
		private final Assignment cKeyParamsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cKeyParamsParamParserRuleCall_7_1_0 = (RuleCall)cKeyParamsAssignment_7_1.eContents().get(0);
		private final RuleCall cTIMETerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Assignment cTimeParamAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTimeParamParamParserRuleCall_9_0 = (RuleCall)cTimeParamAssignment_9.eContents().get(0);
		
		//EventRelation:
		//	event=Event LPAREN params+=Param (COMMA params+=Param)* RPAREN KEY keyParams+=Param (COMMA keyParams+=Param)* TIME
		//	timeParam=Param;
		@Override public ParserRule getRule() { return rule; }

		//event=Event LPAREN params+=Param (COMMA params+=Param)* RPAREN KEY keyParams+=Param (COMMA keyParams+=Param)* TIME
		//timeParam=Param
		public Group getGroup() { return cGroup; }

		//event=Event
		public Assignment getEventAssignment_0() { return cEventAssignment_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_0_0() { return cEventEventParserRuleCall_0_0; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1() { return cLPARENTerminalRuleCall_1; }

		//params+=Param
		public Assignment getParamsAssignment_2() { return cParamsAssignment_2; }

		//Param
		public RuleCall getParamsParamParserRuleCall_2_0() { return cParamsParamParserRuleCall_2_0; }

		//(COMMA params+=Param)*
		public Group getGroup_3() { return cGroup_3; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_3_0() { return cCOMMATerminalRuleCall_3_0; }

		//params+=Param
		public Assignment getParamsAssignment_3_1() { return cParamsAssignment_3_1; }

		//Param
		public RuleCall getParamsParamParserRuleCall_3_1_0() { return cParamsParamParserRuleCall_3_1_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_4() { return cRPARENTerminalRuleCall_4; }

		//KEY
		public RuleCall getKEYTerminalRuleCall_5() { return cKEYTerminalRuleCall_5; }

		//keyParams+=Param
		public Assignment getKeyParamsAssignment_6() { return cKeyParamsAssignment_6; }

		//Param
		public RuleCall getKeyParamsParamParserRuleCall_6_0() { return cKeyParamsParamParserRuleCall_6_0; }

		//(COMMA keyParams+=Param)*
		public Group getGroup_7() { return cGroup_7; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_7_0() { return cCOMMATerminalRuleCall_7_0; }

		//keyParams+=Param
		public Assignment getKeyParamsAssignment_7_1() { return cKeyParamsAssignment_7_1; }

		//Param
		public RuleCall getKeyParamsParamParserRuleCall_7_1_0() { return cKeyParamsParamParserRuleCall_7_1_0; }

		//TIME
		public RuleCall getTIMETerminalRuleCall_8() { return cTIMETerminalRuleCall_8; }

		//timeParam=Param
		public Assignment getTimeParamAssignment_9() { return cTimeParamAssignment_9; }

		//Param
		public RuleCall getTimeParamParamParserRuleCall_9_0() { return cTimeParamParamParserRuleCall_9_0; }
	}

	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Param");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Param:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }

		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}

	public class CommitmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Commitment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCOMMITTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cLabelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLabelIDTerminalRuleCall_1_0 = (RuleCall)cLabelAssignment_1.eContents().get(0);
		private final Assignment cDebtorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDebtorIDTerminalRuleCall_2_0 = (RuleCall)cDebtorAssignment_2.eContents().get(0);
		private final RuleCall cTOTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cCreditorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCreditorIDTerminalRuleCall_4_0 = (RuleCall)cCreditorAssignment_4.eContents().get(0);
		private final RuleCall cCREATETerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cTriggerAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTriggerEExprParserRuleCall_6_0 = (RuleCall)cTriggerAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final RuleCall cDETACHTerminalRuleCall_7_0 = (RuleCall)cGroup_7.eContents().get(0);
		private final Assignment cAntecedentAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAntecedentEExprParserRuleCall_7_1_0 = (RuleCall)cAntecedentAssignment_7_1.eContents().get(0);
		private final RuleCall cDISCHARGETerminalRuleCall_8 = (RuleCall)cGroup.eContents().get(8);
		private final Assignment cConsequentAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cConsequentEExprParserRuleCall_9_0 = (RuleCall)cConsequentAssignment_9.eContents().get(0);
		
		//Commitment:
		//	COMMIT label=ID debtor=ID TO creditor=ID CREATE trigger=EExpr (DETACH antecedent=EExpr)? DISCHARGE consequent=EExpr;
		@Override public ParserRule getRule() { return rule; }

		//COMMIT label=ID debtor=ID TO creditor=ID CREATE trigger=EExpr (DETACH antecedent=EExpr)? DISCHARGE consequent=EExpr
		public Group getGroup() { return cGroup; }

		//COMMIT
		public RuleCall getCOMMITTerminalRuleCall_0() { return cCOMMITTerminalRuleCall_0; }

		//label=ID
		public Assignment getLabelAssignment_1() { return cLabelAssignment_1; }

		//ID
		public RuleCall getLabelIDTerminalRuleCall_1_0() { return cLabelIDTerminalRuleCall_1_0; }

		//debtor=ID
		public Assignment getDebtorAssignment_2() { return cDebtorAssignment_2; }

		//ID
		public RuleCall getDebtorIDTerminalRuleCall_2_0() { return cDebtorIDTerminalRuleCall_2_0; }

		//TO
		public RuleCall getTOTerminalRuleCall_3() { return cTOTerminalRuleCall_3; }

		//creditor=ID
		public Assignment getCreditorAssignment_4() { return cCreditorAssignment_4; }

		//ID
		public RuleCall getCreditorIDTerminalRuleCall_4_0() { return cCreditorIDTerminalRuleCall_4_0; }

		//CREATE
		public RuleCall getCREATETerminalRuleCall_5() { return cCREATETerminalRuleCall_5; }

		//trigger=EExpr
		public Assignment getTriggerAssignment_6() { return cTriggerAssignment_6; }

		//EExpr
		public RuleCall getTriggerEExprParserRuleCall_6_0() { return cTriggerEExprParserRuleCall_6_0; }

		//(DETACH antecedent=EExpr)?
		public Group getGroup_7() { return cGroup_7; }

		//DETACH
		public RuleCall getDETACHTerminalRuleCall_7_0() { return cDETACHTerminalRuleCall_7_0; }

		//antecedent=EExpr
		public Assignment getAntecedentAssignment_7_1() { return cAntecedentAssignment_7_1; }

		//EExpr
		public RuleCall getAntecedentEExprParserRuleCall_7_1_0() { return cAntecedentEExprParserRuleCall_7_1_0; }

		//DISCHARGE
		public RuleCall getDISCHARGETerminalRuleCall_8() { return cDISCHARGETerminalRuleCall_8; }

		//consequent=EExpr
		public Assignment getConsequentAssignment_9() { return cConsequentAssignment_9; }

		//EExpr
		public RuleCall getConsequentEExprParserRuleCall_9_0() { return cConsequentEExprParserRuleCall_9_0; }
	}

	public class EExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cEExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cEXCEPTTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightOExprParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//EExpr returns Expr:
		//	OExpr ({EExpr.left=current} EXCEPT right=OExpr)*;
		@Override public ParserRule getRule() { return rule; }

		//OExpr ({EExpr.left=current} EXCEPT right=OExpr)*
		public Group getGroup() { return cGroup; }

		//OExpr
		public RuleCall getOExprParserRuleCall_0() { return cOExprParserRuleCall_0; }

		//({EExpr.left=current} EXCEPT right=OExpr)*
		public Group getGroup_1() { return cGroup_1; }

		//{EExpr.left=current}
		public Action getEExprLeftAction_1_0() { return cEExprLeftAction_1_0; }

		//EXCEPT
		public RuleCall getEXCEPTTerminalRuleCall_1_1() { return cEXCEPTTerminalRuleCall_1_1; }

		//right=OExpr
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//OExpr
		public RuleCall getRightOExprParserRuleCall_1_2_0() { return cRightOExprParserRuleCall_1_2_0; }
	}

	public class OExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cORTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAExprParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OExpr returns Expr:
		//	AExpr ({OExpr.left=current} OR right=AExpr)*;
		@Override public ParserRule getRule() { return rule; }

		//AExpr ({OExpr.left=current} OR right=AExpr)*
		public Group getGroup() { return cGroup; }

		//AExpr
		public RuleCall getAExprParserRuleCall_0() { return cAExprParserRuleCall_0; }

		//({OExpr.left=current} OR right=AExpr)*
		public Group getGroup_1() { return cGroup_1; }

		//{OExpr.left=current}
		public Action getOExprLeftAction_1_0() { return cOExprLeftAction_1_0; }

		//OR
		public RuleCall getORTerminalRuleCall_1_1() { return cORTerminalRuleCall_1_1; }

		//right=AExpr
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//AExpr
		public RuleCall getRightAExprParserRuleCall_1_2_0() { return cRightAExprParserRuleCall_1_2_0; }
	}

	public class AExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cANDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightWExprParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AExpr returns Expr:
		//	WExpr ({AExpr.left=current} AND right=WExpr)*;
		@Override public ParserRule getRule() { return rule; }

		//WExpr ({AExpr.left=current} AND right=WExpr)*
		public Group getGroup() { return cGroup; }

		//WExpr
		public RuleCall getWExprParserRuleCall_0() { return cWExprParserRuleCall_0; }

		//({AExpr.left=current} AND right=WExpr)*
		public Group getGroup_1() { return cGroup_1; }

		//{AExpr.left=current}
		public Action getAExprLeftAction_1_0() { return cAExprLeftAction_1_0; }

		//AND
		public RuleCall getANDTerminalRuleCall_1_1() { return cANDTerminalRuleCall_1_1; }

		//right=WExpr
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//WExpr
		public RuleCall getRightWExprParserRuleCall_1_2_0() { return cRightWExprParserRuleCall_1_2_0; }
	}

	public class WExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cWExprLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cWHERETerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightSTRINGTerminalRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//WExpr returns Expr:
		//	BExpr ({WExpr.left=current} WHERE right=STRING)*;
		@Override public ParserRule getRule() { return rule; }

		//BExpr ({WExpr.left=current} WHERE right=STRING)*
		public Group getGroup() { return cGroup; }

		//BExpr
		public RuleCall getBExprParserRuleCall_0() { return cBExprParserRuleCall_0; }

		//({WExpr.left=current} WHERE right=STRING)*
		public Group getGroup_1() { return cGroup_1; }

		//{WExpr.left=current}
		public Action getWExprLeftAction_1_0() { return cWExprLeftAction_1_0; }

		//WHERE
		public RuleCall getWHERETerminalRuleCall_1_1() { return cWHERETerminalRuleCall_1_1; }

		//right=STRING
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//STRING
		public RuleCall getRightSTRINGTerminalRuleCall_1_2_0() { return cRightSTRINGTerminalRuleCall_1_2_0; }
	}

	public class BExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BExpr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntervalParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cLPARENTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cEExprParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cRPARENTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		
		//BExpr returns Expr:
		//	Interval | LPAREN EExpr RPAREN;
		@Override public ParserRule getRule() { return rule; }

		//Interval | LPAREN EExpr RPAREN
		public Alternatives getAlternatives() { return cAlternatives; }

		//Interval
		public RuleCall getIntervalParserRuleCall_0() { return cIntervalParserRuleCall_0; }

		//LPAREN EExpr RPAREN
		public Group getGroup_1() { return cGroup_1; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1_0() { return cLPARENTerminalRuleCall_1_0; }

		//EExpr
		public RuleCall getEExprParserRuleCall_1_1() { return cEExprParserRuleCall_1_1; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_1_2() { return cRPARENTerminalRuleCall_1_2; }
	}

	public class IntervalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Interval");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cEventAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_0_0 = (RuleCall)cEventAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cEventAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_1_0_0 = (RuleCall)cEventAssignment_1_0.eContents().get(0);
		private final RuleCall cLBRACKETTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cLTimeAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cLTimeTimeStampParserRuleCall_1_2_0 = (RuleCall)cLTimeAssignment_1_2.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final Assignment cRTimeAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cRTimeTimeStampParserRuleCall_1_4_0 = (RuleCall)cRTimeAssignment_1_4.eContents().get(0);
		private final RuleCall cRBRACKETTerminalRuleCall_1_5 = (RuleCall)cGroup_1.eContents().get(5);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cEventAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_2_0_0 = (RuleCall)cEventAssignment_2_0.eContents().get(0);
		private final RuleCall cLBRACKETTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final RuleCall cCOMMATerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final Assignment cRTimeAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cRTimeTimeStampParserRuleCall_2_3_0 = (RuleCall)cRTimeAssignment_2_3.eContents().get(0);
		private final RuleCall cRBRACKETTerminalRuleCall_2_4 = (RuleCall)cGroup_2.eContents().get(4);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cEventAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_3_0_0 = (RuleCall)cEventAssignment_3_0.eContents().get(0);
		private final RuleCall cLBRACKETTerminalRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Assignment cLTimeAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cLTimeTimeStampParserRuleCall_3_2_0 = (RuleCall)cLTimeAssignment_3_2.eContents().get(0);
		private final RuleCall cCOMMATerminalRuleCall_3_3 = (RuleCall)cGroup_3.eContents().get(3);
		private final RuleCall cRBRACKETTerminalRuleCall_3_4 = (RuleCall)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Assignment cEventAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final RuleCall cEventEventParserRuleCall_4_0_0 = (RuleCall)cEventAssignment_4_0.eContents().get(0);
		private final RuleCall cLBRACKETTerminalRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final RuleCall cCOMMATerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final RuleCall cRBRACKETTerminalRuleCall_4_3 = (RuleCall)cGroup_4.eContents().get(3);
		
		//// Equivalent to the first option
		//Interval returns Expr:
		//	event=Event | event=Event LBRACKET lTime=TimeStamp COMMA rTime=TimeStamp RBRACKET | event=Event LBRACKET COMMA
		//	rTime=TimeStamp RBRACKET | event=Event LBRACKET lTime=TimeStamp COMMA RBRACKET | event=Event LBRACKET COMMA RBRACKET;
		@Override public ParserRule getRule() { return rule; }

		//event=Event | event=Event LBRACKET lTime=TimeStamp COMMA rTime=TimeStamp RBRACKET | event=Event LBRACKET COMMA
		//rTime=TimeStamp RBRACKET | event=Event LBRACKET lTime=TimeStamp COMMA RBRACKET | event=Event LBRACKET COMMA RBRACKET
		public Alternatives getAlternatives() { return cAlternatives; }

		//event=Event
		public Assignment getEventAssignment_0() { return cEventAssignment_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_0_0() { return cEventEventParserRuleCall_0_0; }

		//event=Event LBRACKET lTime=TimeStamp COMMA rTime=TimeStamp RBRACKET
		public Group getGroup_1() { return cGroup_1; }

		//event=Event
		public Assignment getEventAssignment_1_0() { return cEventAssignment_1_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_1_0_0() { return cEventEventParserRuleCall_1_0_0; }

		//LBRACKET
		public RuleCall getLBRACKETTerminalRuleCall_1_1() { return cLBRACKETTerminalRuleCall_1_1; }

		//lTime=TimeStamp
		public Assignment getLTimeAssignment_1_2() { return cLTimeAssignment_1_2; }

		//TimeStamp
		public RuleCall getLTimeTimeStampParserRuleCall_1_2_0() { return cLTimeTimeStampParserRuleCall_1_2_0; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_1_3() { return cCOMMATerminalRuleCall_1_3; }

		//rTime=TimeStamp
		public Assignment getRTimeAssignment_1_4() { return cRTimeAssignment_1_4; }

		//TimeStamp
		public RuleCall getRTimeTimeStampParserRuleCall_1_4_0() { return cRTimeTimeStampParserRuleCall_1_4_0; }

		//RBRACKET
		public RuleCall getRBRACKETTerminalRuleCall_1_5() { return cRBRACKETTerminalRuleCall_1_5; }

		//event=Event LBRACKET COMMA rTime=TimeStamp RBRACKET
		public Group getGroup_2() { return cGroup_2; }

		//event=Event
		public Assignment getEventAssignment_2_0() { return cEventAssignment_2_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_2_0_0() { return cEventEventParserRuleCall_2_0_0; }

		//LBRACKET
		public RuleCall getLBRACKETTerminalRuleCall_2_1() { return cLBRACKETTerminalRuleCall_2_1; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2_2() { return cCOMMATerminalRuleCall_2_2; }

		//rTime=TimeStamp
		public Assignment getRTimeAssignment_2_3() { return cRTimeAssignment_2_3; }

		//TimeStamp
		public RuleCall getRTimeTimeStampParserRuleCall_2_3_0() { return cRTimeTimeStampParserRuleCall_2_3_0; }

		//RBRACKET
		public RuleCall getRBRACKETTerminalRuleCall_2_4() { return cRBRACKETTerminalRuleCall_2_4; }

		//event=Event LBRACKET lTime=TimeStamp COMMA RBRACKET
		public Group getGroup_3() { return cGroup_3; }

		//event=Event
		public Assignment getEventAssignment_3_0() { return cEventAssignment_3_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_3_0_0() { return cEventEventParserRuleCall_3_0_0; }

		//LBRACKET
		public RuleCall getLBRACKETTerminalRuleCall_3_1() { return cLBRACKETTerminalRuleCall_3_1; }

		//lTime=TimeStamp
		public Assignment getLTimeAssignment_3_2() { return cLTimeAssignment_3_2; }

		//TimeStamp
		public RuleCall getLTimeTimeStampParserRuleCall_3_2_0() { return cLTimeTimeStampParserRuleCall_3_2_0; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_3_3() { return cCOMMATerminalRuleCall_3_3; }

		//RBRACKET
		public RuleCall getRBRACKETTerminalRuleCall_3_4() { return cRBRACKETTerminalRuleCall_3_4; }

		//event=Event LBRACKET COMMA RBRACKET
		public Group getGroup_4() { return cGroup_4; }

		//event=Event
		public Assignment getEventAssignment_4_0() { return cEventAssignment_4_0; }

		//Event
		public RuleCall getEventEventParserRuleCall_4_0_0() { return cEventEventParserRuleCall_4_0_0; }

		//LBRACKET
		public RuleCall getLBRACKETTerminalRuleCall_4_1() { return cLBRACKETTerminalRuleCall_4_1; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_4_2() { return cCOMMATerminalRuleCall_4_2; }

		//RBRACKET
		public RuleCall getRBRACKETTerminalRuleCall_4_3() { return cRBRACKETTerminalRuleCall_4_3; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cLifeStateAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Alternatives cLifeStateAlternatives_1_0_0 = (Alternatives)cLifeStateAssignment_1_0.eContents().get(0);
		private final RuleCall cLifeStateCREATEDTerminalRuleCall_1_0_0_0 = (RuleCall)cLifeStateAlternatives_1_0_0.eContents().get(0);
		private final RuleCall cLifeStateDETACHEDTerminalRuleCall_1_0_0_1 = (RuleCall)cLifeStateAlternatives_1_0_0.eContents().get(1);
		private final RuleCall cLifeStateDISCHARGEDTerminalRuleCall_1_0_0_2 = (RuleCall)cLifeStateAlternatives_1_0_0.eContents().get(2);
		private final RuleCall cLifeStateEXPIREDTerminalRuleCall_1_0_0_3 = (RuleCall)cLifeStateAlternatives_1_0_0.eContents().get(3);
		private final RuleCall cLifeStateVIOLATEDTerminalRuleCall_1_0_0_4 = (RuleCall)cLifeStateAlternatives_1_0_0.eContents().get(4);
		private final Assignment cLabelAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cLabelIDTerminalRuleCall_1_1_0 = (RuleCall)cLabelAssignment_1_1.eContents().get(0);
		
		//// Require labels instead of nesting
		//Event:
		//	name=ID | lifeState=(CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED) label=ID;
		@Override public ParserRule getRule() { return rule; }

		//name=ID | lifeState=(CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED) label=ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//lifeState=(CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED) label=ID
		public Group getGroup_1() { return cGroup_1; }

		//lifeState=(CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED)
		public Assignment getLifeStateAssignment_1_0() { return cLifeStateAssignment_1_0; }

		//CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED
		public Alternatives getLifeStateAlternatives_1_0_0() { return cLifeStateAlternatives_1_0_0; }

		//CREATED
		public RuleCall getLifeStateCREATEDTerminalRuleCall_1_0_0_0() { return cLifeStateCREATEDTerminalRuleCall_1_0_0_0; }

		//DETACHED
		public RuleCall getLifeStateDETACHEDTerminalRuleCall_1_0_0_1() { return cLifeStateDETACHEDTerminalRuleCall_1_0_0_1; }

		//DISCHARGED
		public RuleCall getLifeStateDISCHARGEDTerminalRuleCall_1_0_0_2() { return cLifeStateDISCHARGEDTerminalRuleCall_1_0_0_2; }

		//EXPIRED
		public RuleCall getLifeStateEXPIREDTerminalRuleCall_1_0_0_3() { return cLifeStateEXPIREDTerminalRuleCall_1_0_0_3; }

		//VIOLATED
		public RuleCall getLifeStateVIOLATEDTerminalRuleCall_1_0_0_4() { return cLifeStateVIOLATEDTerminalRuleCall_1_0_0_4; }

		//label=ID
		public Assignment getLabelAssignment_1_1() { return cLabelAssignment_1_1; }

		//ID
		public RuleCall getLabelIDTerminalRuleCall_1_1_0() { return cLabelIDTerminalRuleCall_1_1_0; }
	}

	public class TimeStampElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TimeStamp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cValSTRINGTerminalRuleCall_0_0 = (RuleCall)cValAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cEventReferenceAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cEventReferenceEventParserRuleCall_1_0_0 = (RuleCall)cEventReferenceAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final RuleCall cPLUSTerminalRuleCall_1_1_0 = (RuleCall)cGroup_1_1.eContents().get(0);
		private final Assignment cShiftAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cShiftINTTerminalRuleCall_1_1_1_0 = (RuleCall)cShiftAssignment_1_1_1.eContents().get(0);
		
		//TimeStamp:
		//	val=STRING | eventReference=Event (PLUS shift=INT)?;
		@Override public ParserRule getRule() { return rule; }

		//val=STRING | eventReference=Event (PLUS shift=INT)?
		public Alternatives getAlternatives() { return cAlternatives; }

		//val=STRING
		public Assignment getValAssignment_0() { return cValAssignment_0; }

		//STRING
		public RuleCall getValSTRINGTerminalRuleCall_0_0() { return cValSTRINGTerminalRuleCall_0_0; }

		//eventReference=Event (PLUS shift=INT)?
		public Group getGroup_1() { return cGroup_1; }

		//eventReference=Event
		public Assignment getEventReferenceAssignment_1_0() { return cEventReferenceAssignment_1_0; }

		//Event
		public RuleCall getEventReferenceEventParserRuleCall_1_0_0() { return cEventReferenceEventParserRuleCall_1_0_0; }

		//(PLUS shift=INT)?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//PLUS
		public RuleCall getPLUSTerminalRuleCall_1_1_0() { return cPLUSTerminalRuleCall_1_1_0; }

		//shift=INT
		public Assignment getShiftAssignment_1_1_1() { return cShiftAssignment_1_1_1; }

		//INT
		public RuleCall getShiftINTTerminalRuleCall_1_1_1_0() { return cShiftINTTerminalRuleCall_1_1_1_0; }
	}
	
	
	private final CupidoElements pCupido;
	private final SchemataElements pSchemata;
	private final EventRelationElements pEventRelation;
	private final ParamElements pParam;
	private final CommitmentElements pCommitment;
	private final EExprElements pEExpr;
	private final OExprElements pOExpr;
	private final AExprElements pAExpr;
	private final WExprElements pWExpr;
	private final BExprElements pBExpr;
	private final IntervalElements pInterval;
	private final EventElements pEvent;
	private final TimeStampElements pTimeStamp;
	private final TerminalRule tSCHEMA;
	private final TerminalRule tKEY;
	private final TerminalRule tTIME;
	private final TerminalRule tCOMMIT;
	private final TerminalRule tCREATE;
	private final TerminalRule tDETACH;
	private final TerminalRule tDISCHARGE;
	private final TerminalRule tTO;
	private final TerminalRule tEXCEPT;
	private final TerminalRule tAND;
	private final TerminalRule tOR;
	private final TerminalRule tWHERE;
	private final TerminalRule tCREATED;
	private final TerminalRule tDETACHED;
	private final TerminalRule tDISCHARGED;
	private final TerminalRule tEXPIRED;
	private final TerminalRule tVIOLATED;
	private final TerminalRule tCOMMA;
	private final TerminalRule tLBRACKET;
	private final TerminalRule tRBRACKET;
	private final TerminalRule tLPAREN;
	private final TerminalRule tRPAREN;
	private final TerminalRule tPLUS;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CupidoGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCupido = new CupidoElements();
		this.pSchemata = new SchemataElements();
		this.pEventRelation = new EventRelationElements();
		this.pParam = new ParamElements();
		this.pCommitment = new CommitmentElements();
		this.pEExpr = new EExprElements();
		this.pOExpr = new OExprElements();
		this.pAExpr = new AExprElements();
		this.pWExpr = new WExprElements();
		this.pBExpr = new BExprElements();
		this.pInterval = new IntervalElements();
		this.pEvent = new EventElements();
		this.pTimeStamp = new TimeStampElements();
		this.tSCHEMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCHEMA");
		this.tKEY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "KEY");
		this.tTIME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TIME");
		this.tCOMMIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMIT");
		this.tCREATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CREATE");
		this.tDETACH = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DETACH");
		this.tDISCHARGE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DISCHARGE");
		this.tTO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TO");
		this.tEXCEPT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EXCEPT");
		this.tAND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "AND");
		this.tOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "OR");
		this.tWHERE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WHERE");
		this.tCREATED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "CREATED");
		this.tDETACHED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DETACHED");
		this.tDISCHARGED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DISCHARGED");
		this.tEXPIRED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EXPIRED");
		this.tVIOLATED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "VIOLATED");
		this.tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMA");
		this.tLBRACKET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LBRACKET");
		this.tRBRACKET = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RBRACKET");
		this.tLPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LPAREN");
		this.tRPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RPAREN");
		this.tPLUS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PLUS");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.Cupido".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Cupido:
	//	Schemata commitments+=Commitment*;
	public CupidoElements getCupidoAccess() {
		return pCupido;
	}
	
	public ParserRule getCupidoRule() {
		return getCupidoAccess().getRule();
	}

	//Schemata:
	//	SCHEMA schemata+=EventRelation+;
	public SchemataElements getSchemataAccess() {
		return pSchemata;
	}
	
	public ParserRule getSchemataRule() {
		return getSchemataAccess().getRule();
	}

	//EventRelation:
	//	event=Event LPAREN params+=Param (COMMA params+=Param)* RPAREN KEY keyParams+=Param (COMMA keyParams+=Param)* TIME
	//	timeParam=Param;
	public EventRelationElements getEventRelationAccess() {
		return pEventRelation;
	}
	
	public ParserRule getEventRelationRule() {
		return getEventRelationAccess().getRule();
	}

	//Param:
	//	name=ID;
	public ParamElements getParamAccess() {
		return pParam;
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}

	//Commitment:
	//	COMMIT label=ID debtor=ID TO creditor=ID CREATE trigger=EExpr (DETACH antecedent=EExpr)? DISCHARGE consequent=EExpr;
	public CommitmentElements getCommitmentAccess() {
		return pCommitment;
	}
	
	public ParserRule getCommitmentRule() {
		return getCommitmentAccess().getRule();
	}

	//EExpr returns Expr:
	//	OExpr ({EExpr.left=current} EXCEPT right=OExpr)*;
	public EExprElements getEExprAccess() {
		return pEExpr;
	}
	
	public ParserRule getEExprRule() {
		return getEExprAccess().getRule();
	}

	//OExpr returns Expr:
	//	AExpr ({OExpr.left=current} OR right=AExpr)*;
	public OExprElements getOExprAccess() {
		return pOExpr;
	}
	
	public ParserRule getOExprRule() {
		return getOExprAccess().getRule();
	}

	//AExpr returns Expr:
	//	WExpr ({AExpr.left=current} AND right=WExpr)*;
	public AExprElements getAExprAccess() {
		return pAExpr;
	}
	
	public ParserRule getAExprRule() {
		return getAExprAccess().getRule();
	}

	//WExpr returns Expr:
	//	BExpr ({WExpr.left=current} WHERE right=STRING)*;
	public WExprElements getWExprAccess() {
		return pWExpr;
	}
	
	public ParserRule getWExprRule() {
		return getWExprAccess().getRule();
	}

	//BExpr returns Expr:
	//	Interval | LPAREN EExpr RPAREN;
	public BExprElements getBExprAccess() {
		return pBExpr;
	}
	
	public ParserRule getBExprRule() {
		return getBExprAccess().getRule();
	}

	//// Equivalent to the first option
	//Interval returns Expr:
	//	event=Event | event=Event LBRACKET lTime=TimeStamp COMMA rTime=TimeStamp RBRACKET | event=Event LBRACKET COMMA
	//	rTime=TimeStamp RBRACKET | event=Event LBRACKET lTime=TimeStamp COMMA RBRACKET | event=Event LBRACKET COMMA RBRACKET;
	public IntervalElements getIntervalAccess() {
		return pInterval;
	}
	
	public ParserRule getIntervalRule() {
		return getIntervalAccess().getRule();
	}

	//// Require labels instead of nesting
	//Event:
	//	name=ID | lifeState=(CREATED | DETACHED | DISCHARGED | EXPIRED | VIOLATED) label=ID;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//TimeStamp:
	//	val=STRING | eventReference=Event (PLUS shift=INT)?;
	public TimeStampElements getTimeStampAccess() {
		return pTimeStamp;
	}
	
	public ParserRule getTimeStampRule() {
		return getTimeStampAccess().getRule();
	}

	////TODO: Found INT in common Terminals but not NUMBER 
	////Number: // TODO: I didn't find a way to use the Xtext Number that some examples use
	////  name = ID;
	//terminal SCHEMA:
	//	"schema";
	public TerminalRule getSCHEMARule() {
		return tSCHEMA;
	} 

	//terminal KEY:
	//	"key";
	public TerminalRule getKEYRule() {
		return tKEY;
	} 

	//terminal TIME:
	//	"time";
	public TerminalRule getTIMERule() {
		return tTIME;
	} 

	//terminal COMMIT:
	//	"commitment";
	public TerminalRule getCOMMITRule() {
		return tCOMMIT;
	} 

	//terminal CREATE:
	//	"create";
	public TerminalRule getCREATERule() {
		return tCREATE;
	} 

	//terminal DETACH:
	//	"detach";
	public TerminalRule getDETACHRule() {
		return tDETACH;
	} 

	//terminal DISCHARGE:
	//	"discharge";
	public TerminalRule getDISCHARGERule() {
		return tDISCHARGE;
	} 

	//terminal TO:
	//	"to";
	public TerminalRule getTORule() {
		return tTO;
	} 

	//terminal EXCEPT:
	//	"except";
	public TerminalRule getEXCEPTRule() {
		return tEXCEPT;
	} 

	//terminal AND:
	//	"and";
	public TerminalRule getANDRule() {
		return tAND;
	} 

	//terminal OR:
	//	"or";
	public TerminalRule getORRule() {
		return tOR;
	} 

	//terminal WHERE:
	//	"where";
	public TerminalRule getWHERERule() {
		return tWHERE;
	} 

	//terminal CREATED:
	//	"created";
	public TerminalRule getCREATEDRule() {
		return tCREATED;
	} 

	//terminal DETACHED:
	//	"detached";
	public TerminalRule getDETACHEDRule() {
		return tDETACHED;
	} 

	//terminal DISCHARGED:
	//	"discharged";
	public TerminalRule getDISCHARGEDRule() {
		return tDISCHARGED;
	} 

	//terminal EXPIRED:
	//	"expired";
	public TerminalRule getEXPIREDRule() {
		return tEXPIRED;
	} 

	//terminal VIOLATED:
	//	"violated";
	public TerminalRule getVIOLATEDRule() {
		return tVIOLATED;
	} 

	//terminal COMMA:
	//	",";
	public TerminalRule getCOMMARule() {
		return tCOMMA;
	} 

	//terminal LBRACKET:
	//	"[";
	public TerminalRule getLBRACKETRule() {
		return tLBRACKET;
	} 

	//terminal RBRACKET:
	//	"]";
	public TerminalRule getRBRACKETRule() {
		return tRBRACKET;
	} 

	//terminal LPAREN:
	//	"(";
	public TerminalRule getLPARENRule() {
		return tLPAREN;
	} 

	//terminal RPAREN:
	//	")";
	public TerminalRule getRPARENRule() {
		return tRPAREN;
	} 

	//terminal PLUS:
	//	"+";
	public TerminalRule getPLUSRule() {
		return tPLUS;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
