/*
* generated by Xtext
*/
package org.xtext.example;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CupidoStandaloneSetup extends CupidoStandaloneSetupGenerated{

	public static void doSetup() {
		new CupidoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

