/*
 * generated by Xtext
 */
package org.xtext.example;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CupidoRuntimeModule extends org.xtext.example.AbstractCupidoRuntimeModule {

}
