/*
 * generated by Xtext
 */
package org.xtext.example.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.services.CupidoGrammarAccess;

@SuppressWarnings("all")
public class CupidoSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CupidoGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BExpr_LPARENTerminalRuleCall_1_0_a;
	protected AbstractElementAlias match_BExpr_LPARENTerminalRuleCall_1_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CupidoGrammarAccess) access;
		match_BExpr_LPARENTerminalRuleCall_1_0_a = new TokenAlias(true, true, grammarAccess.getBExprAccess().getLPARENTerminalRuleCall_1_0());
		match_BExpr_LPARENTerminalRuleCall_1_0_p = new TokenAlias(true, false, grammarAccess.getBExprAccess().getLPARENTerminalRuleCall_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if(ruleCall.getRule() == grammarAccess.getANDRule())
			return getANDToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getCOMMARule())
			return getCOMMAToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getCOMMITRule())
			return getCOMMITToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getCREATERule())
			return getCREATEToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getDETACHRule())
			return getDETACHToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getDISCHARGERule())
			return getDISCHARGEToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getEXCEPTRule())
			return getEXCEPTToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getKEYRule())
			return getKEYToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getLBRACKETRule())
			return getLBRACKETToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getLPARENRule())
			return getLPARENToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getORRule())
			return getORToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getPLUSRule())
			return getPLUSToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getRBRACKETRule())
			return getRBRACKETToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getRPARENRule())
			return getRPARENToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getSCHEMARule())
			return getSCHEMAToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTIMERule())
			return getTIMEToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getTORule())
			return getTOToken(semanticObject, ruleCall, node);
		else if(ruleCall.getRule() == grammarAccess.getWHERERule())
			return getWHEREToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal AND: 'and';
	 */
	protected String getANDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "and";
	}
	
	/**
	 * terminal COMMA: ',';
	 */
	protected String getCOMMAToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ",";
	}
	
	/**
	 * terminal COMMIT: 'commitment';
	 */
	protected String getCOMMITToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "commitment";
	}
	
	/**
	 * terminal CREATE: 'create';
	 */
	protected String getCREATEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "create";
	}
	
	/**
	 * terminal DETACH: 'detach';
	 */
	protected String getDETACHToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "detach";
	}
	
	/**
	 * terminal DISCHARGE: 'discharge';
	 */
	protected String getDISCHARGEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "discharge";
	}
	
	/**
	 * terminal EXCEPT: 'except';
	 */
	protected String getEXCEPTToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "except";
	}
	
	/**
	 * terminal KEY: 'key';
	 */
	protected String getKEYToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "key";
	}
	
	/**
	 * terminal LBRACKET: '[';
	 */
	protected String getLBRACKETToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "[";
	}
	
	/**
	 * terminal LPAREN: '(';
	 */
	protected String getLPARENToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "(";
	}
	
	/**
	 * terminal OR: 'or';
	 */
	protected String getORToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "or";
	}
	
	/**
	 * terminal PLUS: '+';
	 */
	protected String getPLUSToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "+";
	}
	
	/**
	 * terminal RBRACKET: ']';
	 */
	protected String getRBRACKETToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "]";
	}
	
	/**
	 * terminal RPAREN: ')';
	 */
	protected String getRPARENToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ")";
	}
	
	/**
	 * terminal SCHEMA: 'schema';
	 */
	protected String getSCHEMAToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "schema";
	}
	
	/**
	 * terminal TIME: 'time';
	 */
	protected String getTIMEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "time";
	}
	
	/**
	 * terminal TO: 'to';
	 */
	protected String getTOToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "to";
	}
	
	/**
	 * terminal WHERE: 'where';
	 */
	protected String getWHEREToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "where";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_BExpr_LPARENTerminalRuleCall_1_0_a.equals(syntax))
				emit_BExpr_LPARENTerminalRuleCall_1_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if(match_BExpr_LPARENTerminalRuleCall_1_0_p.equals(syntax))
				emit_BExpr_LPARENTerminalRuleCall_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     LPAREN*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) interval=Interval
	 *     (rule start) (ambiguity) {AExpr.left=}
	 *     (rule start) (ambiguity) {EExpr.left=}
	 *     (rule start) (ambiguity) {OExpr.left=}
	 *     (rule start) (ambiguity) {WExpr.left=}
	 */
	protected void emit_BExpr_LPARENTerminalRuleCall_1_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     LPAREN+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {AExpr.left=}
	 *     (rule start) (ambiguity) {EExpr.left=}
	 *     (rule start) (ambiguity) {OExpr.left=}
	 *     (rule start) (ambiguity) {WExpr.left=}
	 */
	protected void emit_BExpr_LPARENTerminalRuleCall_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
