/*
 * generated by Xtext
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.services.CupidoGrammarAccess;

public class CupidoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CupidoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.parser.antlr.internal.InternalCupidoParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.parser.antlr.internal.InternalCupidoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Cupido";
	}
	
	public CupidoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CupidoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
